spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  active:
    profile: dev
  application:
    name: pathfinder
  #cloud:
   # vault:
    #  uri: http://127.0.0.1:8200
     # token: 'hvs.3muobn8Z2Ind7BHAEICc7qrY'
      #kv:
       # enabled: true
  #config:
   # import: vault://
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username}
    password: ${db_password}
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

binding-result-package: org.springframework.validation.BindingResult